name: Install NPM Packages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  install-deps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # or use your project's Node version

      - name: Install dependencies
        run: npm install
